back_end:
  host: 0.0.0.0
  port: 7782
  protocol: tcp
base_model_path: /home/rwkv/RWKV-RAG-models/RWKV-x060-World-7B-v2.1-20240507-ctx4096.pth
device: cuda:3
embedding_path: /home/rwkv/RWKV-RAG-models/bge-m31
num_workers: 1
reranker_path: /home/rwkv/RWKV-RAG-models/BAAIbge-reranker-v2-m3
service_module: llm_service
spawn_method: spawn